-- Run: require(game.ServerScriptService.Server.Tests["BakeryEconomy.spec"])()
return function()
	local E = require(game.ReplicatedStorage.Shared.Economy)
	local s = E.new()
	assert(E.clickValue(s) == 1 and E.goal(s) == 100)
	assert(not E.purchase(s, "power"))
	assert(not E.rebirth(s))
	E.award(s, 10)
	assert(E.purchase(s, "power"))
	assert(s.cookies == 0 and E.clickValue(s) == 2)
	assert(E.cost(s, "power") == 16)
	E.award(s, 25)
	assert(E.purchase(s, "ovens"))
	assert(E.passiveRate(s) == 1)
	E.award(s, 105)
	assert(s.cookies == 105 and s.rebirths == 0 and s.power == 1 and s.ovens == 1, "Rebirth must not be automatic")
	assert(E.rebirth(s))
	assert(s.cookies == 5 and s.rebirths == 1 and s.power == 0 and s.ovens == 0)
	assert(E.clickValue(s) == 2 and E.goal(s) == 500)
	E.award(s, 3000)
	assert(s.cookies == 3005 and s.rebirths == 1)
	assert(E.rebirth(s))
	assert(s.cookies == 2505 and s.rebirths == 2, "One tier per manual activation")
	assert(E.rebirth(s))
	assert(s.cookies == 5 and s.rebirths == 3)
	assert(not E.rebirth(s))
	local before = s.cookies
	E.award(s, 0 / 0); E.award(s, math.huge); E.award(s, -5)
	assert(s.cookies == before)
	assert(not E.purchase(s, "hacked"))
	local max = E.new(); max.rebirths = E.MaxRebirths; max.cookies = E.MaxCurrency
	E.award(max, 1000)
	assert(max.cookies == E.MaxCurrency and E.goal(max) == math.huge)
	assert(not E.rebirth(max))
	max.power = E.MaxUpgrades
	assert(not E.purchase(max, "power"))
	return "PASS: manual-only rebirth, one tier/click, costs, resets, overflow, passive income and caps"
end
